# Otimização Nutricional com Programação Linear

Deve-se desenvolver um software que utilize programação linear na  otimização  das  quantidades  necessárias de  alimentos,  com  o  objetivo  de  atender  às necessidades  nutricionais  de  um  indivíduo  adulto.  A  atividade  começará  com  uma  análise  de uma planilha fornecida, contendo informações nutricionais de diversos alimentos.

*Etapas:*
1. Análise da planilha de informações nutricionais
2. Estudo das necessidades nutricionais dos indivíduos
3. Desenvolvimento do software
4. Apresentação dos resultados

In [16]:
import pandas as pd

In [17]:
#1. Análise da planilha de informações nutricionais
df = pd.read_excel('tabela_alimentos.xls')
display(df)

,Número do Alimento,Descrição dos alimentos,Umidade,Energia,Unnamed: 4,Proteína,Lipídeos,Colesterol,Carboidrato,Fibra Alimentar,...,Cobre,Zinco,Retinol,RE,RAE,Tiamina,Riboflavina,Piridoxina,Niacina,Vitamina C
0,1,"Arroz, integral, cozido",70.138667,123.534893,516.86999,2.58825,1.000333,NaN,25.80975,2.749333,...,0.020333,0.682667,NaN,NaN,NaN,0.08,Tr,0.08,Tr,NaN
1,2,"Arroz, integral, cru",12.179833,359.678002,1504.892761,7.323286,1.864833,NaN,77.450714,4.819167,...,0.074833,1.395167,NaN,NaN,NaN,0.261667,Tr,0.175,4.183333,NaN
2,3,"Arroz, tipo 1, cozido",69.113667,128.258486,536.633504,2.520817,0.227,NaN,28.05985,1.561,...,0.015,0.491333,NaN,NaN,NaN,Tr,Tr,Tr,Tr,NaN
3,4,"Arroz, tipo 1, cru",13.2245,357.789273,1496.990319,7.15854,0.335,NaN,78.759543,1.639167,...,0.114833,1.224833,NaN,NaN,NaN,0.163333,Tr,0.069167,1.116667,NaN
4,5,"Arroz, tipo 2, cozido",68.727667,130.119648,544.420609,2.568417,0.361667,NaN,28.192583,1.069667,...,0.041,0.549333,NaN,NaN,NaN,Tr,Tr,Tr,Tr,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592,593,"Gergelim, semente",3.859333,583.546715,2441.559455,21.164667,50.432667,NaN,21.617666,11.868333,...,1.509667,5.235,NaN,NaN,NaN,0.936667,Tr,0.13,5.923333,Tr
593,594,"Linhaça, semente",6.683,495.096114,2071.534915,14.083867,32.252933,NaN,43.312199,33.502667,...,1.087333,4.388333,NaN,NaN,NaN,0.116667,Tr,0.133333,Tr,Tr
594,595,"Pinhão, cozido",50.513333,174.369902,729.56367,2.980367,0.747,NaN,43.917633,15.603333,...,0.183333,0.827,NaN,NaN,NaN,Tr,Tr,Tr,Tr,27.69
595,596,"Pupunha, cozida",54.46,218.533881,914.345758,2.522917,12.761667,NaN,29.569417,4.253333,...,0.282333,0.291667,NaN,875.444444,437.722222,Tr,0.086667,0.03,Tr,2.18
596,597,"Noz, crua",6.244667,620.06002,2594.331123,13.970801,59.359667,NaN,18.363866,7.249667,...,0.754333,2.064333,NaN,NaN,NaN,0.376667,Tr,0.13,1.083333,Tr

In [18]:
df = df.drop(['Número do Alimento', 'Umidade', 'Unnamed: 4', 'Fibra Alimentar', 'Cinzas', 'Magnésio', 'Número do Alimento', 'Manganês', 'Fósforo', 'Sódio', 'Potássio', 'Cobre', 'Zinco', 'RE', 'Tiamina', 'Riboflavina', 'Piridoxina', 'Niacina'], axis=1)
display(df)

,Descrição dos alimentos,Energia,Proteína,Lipídeos,Colesterol,Carboidrato,Cálcio,Ferro,Retinol,RAE,Vitamina C
0,"Arroz, integral, cozido",123.534893,2.58825,1.000333,NaN,25.80975,5.204,0.262,NaN,NaN,NaN
1,"Arroz, integral, cru",359.678002,7.323286,1.864833,NaN,77.450714,7.818,0.948333,NaN,NaN,NaN
2,"Arroz, tipo 1, cozido",128.258486,2.520817,0.227,NaN,28.05985,3.544333,0.076667,NaN,NaN,NaN
3,"Arroz, tipo 1, cru",357.789273,7.15854,0.335,NaN,78.759543,4.414333,0.677747,NaN,NaN,NaN
4,"Arroz, tipo 2, cozido",130.119648,2.568417,0.361667,NaN,28.192583,3.333667,0.050333,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
592,"Gergelim, semente",583.546715,21.164667,50.432667,NaN,21.617666,825.446333,5.447667,NaN,NaN,Tr
593,"Linhaça, semente",495.096114,14.083867,32.252933,NaN,43.312199,211.497667,4.697,NaN,NaN,Tr
594,"Pinhão, cozido",174.369902,2.980367,0.747,NaN,43.917633,15.767333,0.755333,NaN,NaN,27.69
595,"Pupunha, cozida",218.533881,2.522917,12.761667,NaN,29.569417,27.586333,0.518667,NaN,437.722222,2.18
596,"Noz, crua",620.06002,13.970801,59.359667,NaN,18.363866,105.306333,2.035,NaN,NaN,Tr

In [25]:
df = df.fillna(0)
display(df)

,Descrição dos alimentos,Energia,Proteína,Lipídeos,Colesterol,Carboidrato,Cálcio,Ferro,Retinol,RAE,Vitamina C
0,"Arroz, integral, cozido",123.534893,2.58825,1.000333,0,25.80975,5.204,0.262,0,0,0
1,"Arroz, integral, cru",359.678002,7.323286,1.864833,0,77.450714,7.818,0.948333,0,0,0
2,"Arroz, tipo 1, cozido",128.258486,2.520817,0.227,0,28.05985,3.544333,0.076667,0,0,0
3,"Arroz, tipo 1, cru",357.789273,7.15854,0.335,0,78.759543,4.414333,0.677747,0,0,0
4,"Arroz, tipo 2, cozido",130.119648,2.568417,0.361667,0,28.192583,3.333667,0.050333,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
592,"Gergelim, semente",583.546715,21.164667,50.432667,0,21.617666,825.446333,5.447667,0,0,Tr
593,"Linhaça, semente",495.096114,14.083867,32.252933,0,43.312199,211.497667,4.697,0,0,Tr
594,"Pinhão, cozido",174.369902,2.980367,0.747,0,43.917633,15.767333,0.755333,0,0,27.69
595,"Pupunha, cozida",218.533881,2.522917,12.761667,0,29.569417,27.586333,0.518667,0,437.722222,2.18
596,"Noz, crua",620.06002,13.970801,59.359667,0,18.363866,105.306333,2.035,0,0,Tr

In [29]:
lista_pessoas = [
    {'Sexo': 'Homem', 'Peso': 50.0, 'Proteínas': 40.0, 'Carboidratos': 200.0, 'Gorduras': 50.0, 'Vitamina A': 900.0, 'Vitamina C': 90.0, 'Cálcio': 1000.0, 'Ferro': 8.0},
    {'Sexo': 'Homem', 'Peso': 60.0, 'Proteínas': 48.0, 'Carboidratos': 240.0, 'Gorduras': 60.0, 'Vitamina A': 900.0, 'Vitamina C': 90.0, 'Cálcio': 1000.0, 'Ferro': 8.0},
    {'Sexo': 'Homem', 'Peso': 70.0, 'Proteínas': 56.0, 'Carboidratos': 280.0, 'Gorduras': 70.0, 'Vitamina A': 900.0, 'Vitamina C': 90.0, 'Cálcio': 1000.0, 'Ferro': 8.0},
    {'Sexo': 'Homem', 'Peso': 80.0, 'Proteínas': 64.0, 'Carboidratos': 320.0, 'Gorduras': 80.0, 'Vitamina A': 900.0, 'Vitamina C': 90.0, 'Cálcio': 1000.0, 'Ferro': 8.0},
    {'Sexo': 'Homem', 'Peso': 90.0, 'Proteínas': 72.0, 'Carboidratos': 360.0, 'Gorduras': 90.0, 'Vitamina A': 900.0, 'Vitamina C': 90.0, 'Cálcio': 1000.0, 'Ferro': 8.0},
    {'Sexo': 'Homem', 'Peso': 100.0, 'Proteínas': 80.0, 'Carboidratos': 400.0, 'Gorduras': 100.0, 'Vitamina A': 900.0, 'Vitamina C': 90.0, 'Cálcio': 1000.0, 'Ferro': 8.0},
    {'Sexo': 'Mulher', 'Peso': 50.0, 'Proteínas': 40.0, 'Carboidratos': 200.0, 'Gorduras': 50.0, 'Vitamina A': 700.0, 'Vitamina C': 75.0, 'Cálcio': 1000.0, 'Ferro': 18.0},
    {'Sexo': 'Mulher', 'Peso': 55.0, 'Proteínas': 43.0, 'Carboidratos': 215.0, 'Gorduras': 55.0, 'Vitamina A': 700.0, 'Vitamina C': 75.0, 'Cálcio': 1000.0, 'Ferro': 18.0},
    {'Sexo': 'Mulher', 'Peso': 60.0, 'Proteínas': 46.0, 'Carboidratos': 230.0, 'Gorduras': 60.0, 'Vitamina A': 700.0, 'Vitamina C': 75.0, 'Cálcio': 1000.0, 'Ferro': 18.0},
    {'Sexo': 'Mulher', 'Peso': 65.0, 'Proteínas': 49.0, 'Carboidratos': 245.0, 'Gorduras': 65.0, 'Vitamina A': 700.0, 'Vitamina C': 75.0, 'Cálcio': 1000.0, 'Ferro': 18.0},
    {'Sexo': 'Mulher', 'Peso': 70.0, 'Proteínas': 52.0, 'Carboidratos': 260.0, 'Gorduras': 70.0, 'Vitamina A': 700.0, 'Vitamina C': 75.0, 'Cálcio': 1000.0, 'Ferro': 18.0},
]

df_necessidades = pd.DataFrame(lista_pessoas)
#df_necessidades.set_index('Sexo', inplace=True)
df_necessidades

,Sexo,Peso,Proteínas,Carboidratos,Gorduras,Vitamina A,Vitamina C,Cálcio,Ferro
0,Homem,50.0,40.0,200.0,50.0,900.0,90.0,1000.0,8.0
1,Homem,60.0,48.0,240.0,60.0,900.0,90.0,1000.0,8.0
2,Homem,70.0,56.0,280.0,70.0,900.0,90.0,1000.0,8.0
3,Homem,80.0,64.0,320.0,80.0,900.0,90.0,1000.0,8.0
4,Homem,90.0,72.0,360.0,90.0,900.0,90.0,1000.0,8.0
5,Homem,100.0,80.0,400.0,100.0,900.0,90.0,1000.0,8.0
6,Mulher,50.0,40.0,200.0,50.0,700.0,75.0,1000.0,18.0
7,Mulher,55.0,43.0,215.0,55.0,700.0,75.0,1000.0,18.0
8,Mulher,60.0,46.0,230.0,60.0,700.0,75.0,1000.0,18.0
9,Mulher,65.0,49.0,245.0,65.0,700.0,75.0,1000.0,18.0
10,Mulher,70.0,52.0,260.0,70.0,700.0,75.0,1000.0,18.0

In [71]:
peso_individuo = int(input('Insira seu peso: '))
sexo_individuo = str(input('Insira seu sexo biológico: (homem ou mulher)  '))
alergia_glutem = str(input('Você é alérgico(a) a glutem? Responda com S para sim e N para não: '))
dieta = int(input('Escolha uma dieta: Responda 1 para Emagrecer, 2 para Engordar e 3 para Sem Dieta: '))

Insira seu peso: 70
Insira seu sexo biológico: (homem ou mulher)  homem
Você é alérgico(a) a glutem? Responda com S para sim e N para não: s
Escolha uma dieta: Responda 1 para Emagrecer, 2 para Engordar e 3 para Sem Dieta: 3

In [72]:
if sexo_individuo == 'mulher' or 'Mulher':
    proteinas_mulher = (peso_individuo * 46) // 60
    carb_mulher = (peso_individuo * 230) // 60
    gorduras_mulher = (peso_individuo * 60) // 60
    vita_mulher = 700
    vitc_mulher = 75
    calcio_mulher = 1000
    ferro_mulher = 18
    print('Necessidades nutricionais diárias:')
    print(f'Proteínas: {proteinas_mulher}g por dia')
    print(f'Carboidrato: {carb_mulher}g por dia')
    print(f'Gorduras: {gorduras_mulher}g por dia')
    print(f'Vitamina A: {vita_mulher}mcg por dia')
    print(f'Vitamina C: {vitc_mulher}mg por dia')
    print(f'Cálcio: {calcio_mulher}mg por dia')
    print(f'Ferro: {ferro_mulher}mg por dia')
else:
    sexo_individuo == 'homem' or 'Homem'
    proteinas_homem = (peso_individuo * 48) / 60
    carb_homem = (peso_individuo * 240) // 60
    gorduras_homem = (peso_individuo * 60) // 60
    vita_homem = 900
    vitc_homem = 90
    calcio_homem = 1000
    ferro_homem = 8
    print('Necessidades nutricionais diárias:')
    print(f'Proteínas {proteinas_homem} gramas por dia')
    print(f'Carboidrato: {carb_homem}g por dia')
    print(f'Gorduras: {gorduras_homem}g por dia')
    print(f'Vitamina A: {vita_homem}mcg por dia')
    print(f'Vitamina C: {vitc_homem}mg por dia')
    print(f'Cálcio: {calcio_homem}mg por dia')
    print(f'Ferro: {ferro_homem}mg por dia')

Necessidades nutricionais diárias:
Proteínas: 53g por dia
Carboidrato: 268g por dia
Gorduras: 70g por dia
Vitamina A: 700mcg por dia
Vitamina C: 75mg por dia
Cálcio: 1000mg por dia
Ferro: 18mg por dia